# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np
np.zeros((100), int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [2]:
np.ones((100), int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### 3.Создать вектор размера 100, заполненный числом 3

In [3]:
np.full(100,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [4]:
3*np.ones((100), int)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [7]:
a = np.arange(9).reshape(3,3)
print(a)
a[1],a[2]=a[2],a[1].copy()
a

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

#### 6. Создать вектор со значениями от 10 до 100

In [8]:
np.arange(10,101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [9]:
reversed_arr = np.arange(10,101)[::-1]
print(reversed_arr)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [10]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [11]:
Z = np.array([1,2,3,4,5])
Z0 = np.zeros((len(Z) + (len(Z)-1)*3),dtype=int)
# каждый 4 элемент
Z0[::4] = Z
print(Z0)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 10. Создать 3x3 единичную матрицу

In [12]:
np.identity(3, int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [14]:
np.random.random((3,3,3))

array([[[0.92427228, 0.1455221 , 0.33343604],
        [0.30313737, 0.3835681 , 0.94898033],
        [0.74787114, 0.902987  , 0.79097225]],

       [[0.9328211 , 0.36211874, 0.67474014],
        [0.83471159, 0.8608019 , 0.85549316],
        [0.91324598, 0.42391056, 0.62795537]],

       [[0.71436345, 0.08589983, 0.99465772],
        [0.86463418, 0.76855393, 0.39176288],
        [0.40704484, 0.6588    , 0.27216793]]])

In [15]:
np.random.randint(1,10,(3,3,3))

array([[[9, 6, 3],
        [6, 5, 2],
        [3, 6, 5]],

       [[1, 2, 3],
        [5, 4, 1],
        [3, 3, 9]],

       [[6, 3, 2],
        [3, 9, 5],
        [7, 2, 9]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [20]:
a = np.random.randint(1,1000,(10,10))
print(a)
print(a.min())
print(a.max())

[[169 902 462 257 204 425 127 732 278 766]
 [353 657 350 558 937 205  67 754 836 278]
 [249 506 947 948 884 880 375 839 777 797]
 [363 330  35 911 610 460 873 282 817  52]
 [788  58 301 267 389 222 166 760 216 957]
 [142 765 268 809 625 783 457 252 972 696]
 [119  99 285 222 316 401 569 717 973 605]
 [977 721 153 626 113 778 822 877 632 508]
 [160 442 619 834 959 264 215 668 820  97]
 [ 73 334 903  88 877 580 459 156 594 217]]
35
977


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [21]:
a = np.random.random(30)
print(np.mean(a))

0.45066619244919903


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [22]:
a = np.ones((5,5), int)
a[1:-1,1:-1] = 0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [16]:
a = np.ones((10,10), int)
b = np.ones((10,10), int)
for el in range(5):
    if el%2 == 1:
        a[el:-el,el:-el] = 0
    else:
        a[el:-el,el:-el] = 1
print(a, '\n')
for el in range(5):
    b[el:-el,el:-el] = el+1
print(b, '\n')
a @ b

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 0 1 0 1]
 [1 0 1 0 1 1 0 1 0 1]
 [1 0 1 0 1 1 0 1 0 1]
 [1 0 1 0 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]] 

[[1 1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1 1]] 



array([[10, 18, 24, 28, 30, 30, 28, 24, 18, 10],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 8, 14, 20, 24, 26, 26, 24, 20, 14,  8],
       [ 4,  6,  8,  8,  8,  8,  8,  8,  6,  4],
       [ 6, 10, 14, 16, 18, 18, 16, 14, 10,  6],
       [ 6, 10, 14, 16, 18, 18, 16, 14, 10,  6],
       [ 4,  6,  8,  8,  8,  8,  8,  8,  6,  4],
       [ 8, 14, 20, 24, 26, 26, 24, 20, 14,  8],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [10, 18, 24, 28, 30, 30, 28, 24, 18, 10]])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [107]:
a = np.diag([1,2,2,4], k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [121]:
a = np.ones((8,8), dtype=int)
a[1::2,::2] = 0
a[::2,1::2] = 0
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [125]:
# получить индексы элементов многомерного массива по индексам тех же самых элементов в его плоском представлении
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [131]:
np.tile(np.array([[1,0],[0,1]]),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [133]:
a = np.ones((5,3), int)
b = np.ones((3,2), int)
a.dot(b)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [141]:
a = np.arange(10)
a[(3<a) & (a<8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [4]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [124]:
def generate():
    for x in range(10):
        yield x
# fromiter - создает одномерный массив из итерируемого объекта
a = np.fromiter(generate(),dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [148]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [24]:
a = np.random.random(10)
print(a)
a.sort()
a

[0.86621101 0.58769354 0.28866239 0.6534528  0.17751498 0.43079812
 0.66539889 0.95892607 0.71214858 0.54647757]


array([0.17751498, 0.28866239, 0.43079812, 0.54647757, 0.58769354,
       0.6534528 , 0.66539889, 0.71214858, 0.86621101, 0.95892607])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [30]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)

False


#### 28. Сделать массив неизменяемым

In [129]:
a = np.zeros(10)
a.flags.writeable = False
a[1] = 1

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [197]:
a = np.random.randint(0,10,20)
a.sort()
n = 5
print(a)
print(a[-n:])

[0 0 0 0 0 2 2 2 3 3 4 4 5 5 5 7 8 8 8 8]
[7 8 8 8 8]


In [6]:
a = np.random.randint(1,100,6)
n = 3
print(a)
print (a[np.argpartition(a,n)[-n:]]) 

[29 10 90 28 24  5]
[28 29 90]


#### 30. Заменить максимальный элемент на ноль

In [145]:
a = np.random.randint(0,30,3)
print(a)
a[a==a.max()]=0
print(a)

[10 28  5]
[10  0  5]


In [148]:
a = np.random.randint(0,30,3)
print(a)
a[a.argmax()]=0
print(a)

[15 21  8]
[15  0  8]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [32]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(a)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [33]:
a = np.arange(3)
b = a + 1.5
c = 1.0 / np.subtract.outer(a, b)
c

array([[-0.66666667, -0.4       , -0.28571429],
       [-2.        , -0.66666667, -0.4       ],
       [ 2.        , -2.        , -0.66666667]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [29]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [35]:
# set_printoptions - Параметры выводы
# threshold - Задает общее количество элементов массива, превышение которого запускает механизм сокращенного вывода
np.set_printoptions(threshold=np.inf)
a = np.zeros((25,25), int)
print(a)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [36]:
a = np.arange(15)
x = 16
print(a)
index = (np.abs(a-x)).argmin()
print(a[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
14


#### 36. Преобразовать массив из float в int

In [51]:
a = np.arange(10, dtype=np.int32)
print(a)
a = a.astype(np.float32, copy=False)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [53]:
a = np.arange(9).reshape(3,3)
print(a)
for index, value in np.ndenumerate(a):
    print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [68]:
n = 10
p = 3
a = np.zeros((n,n), int)
# replace - повторение элементов в выборке
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 39. Отнять среднее из каждой строки в матрице

In [66]:
a = np.random.randint(0,10,(2,2))
print(a)
# axis - Позволяет задать ось или несколько осей вдоль которых вычисляется среднее арифметическое
# axis 0 - столбцы, 1-строки
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[8 9]
 [1 0]]
[[-0.5  0.5]
 [ 0.5 -0.5]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [70]:
a = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(a)
# a[:,n] - n-ый столбик
# argsort() - возвращает список индексов отсортированный по элементам
print(a[a[:,n].argsort()])

[[4 9 2]
 [7 0 2]
 [9 3 6]]
[[7 0 2]
 [9 3 6]
 [4 9 2]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [88]:
a = np.random.randint(0,3,(3,10))
print(a)
# False если есть нулевой столбик
print(a.any(axis=0))
# меняем на противоположное значение
print(~a.any(axis=0))
# по сути применяем операцию or
print((~a.any(axis=0)).any())

[[2 0 1 0 1 2 1 1 1 2]
 [0 1 0 0 2 2 0 0 1 0]
 [1 1 1 1 1 0 2 0 1 0]]
[ True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False]
False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [17]:
a = np.ones(10, int)
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [18]:
# создаем список из 20 элементов, в диапазоне от 0 до длины a (рандомные индексы)
# b - массив индексов элементов, к которым прибавляем 1
b = np.random.randint(0,len(a),20)
print(b)

[0 2 2 8 6 5 5 4 2 6 7 9 8 7 1 5 4 6 2 0]


In [19]:
# bincount - возвращает количество вхождений значений в массиве
# minlength - минимальная длина выходного массива
# первый элемент этого массива - число вхождений 0 в массиве b, и тд
print(np.bincount(b, minlength=len(a)))

[2 1 4 0 2 3 3 2 2 1]


In [20]:
a += np.bincount(b, minlength=len(a))
print(a)

[3 2 5 1 3 4 4 3 3 2]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [38]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [99]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[53 57 49 49]
 [62 63 41 51]
 [60 37 67 79]]
